FROM busybox AS builder
WORKDIR /rootfs
RUN wget https://download.openvz.org/template/precreated/contrib/altlinux-p6-20120321-x86_64.tar.gz && \
tar -xf altlinux-p6-20120321-x86_64.tar.gz && \
rm -rf altlinux-p6-20120321-x86_64.tar.gz
RUN echo "rpm [cert6] http://mirror.yandex.ru/altlinux/p6/branch x86_64 classic" > /rootfs/etc/apt/sources.list.d/yandex.list && \
echo "rpm [cert6] http://mirror.yandex.ru/altlinux/p6/branch noarch classic" >> /rootfs/etc/apt/sources.list.d/yandex.list && \
echo "rpm [cert6] http://mirror.yandex.ru/altlinux/p5/branch x86_64 classic" >> /rootfs/etc/apt/sources.list.d/yandex.list

FROM scratch
COPY --from=builder /rootfs /
RUN apt-get update && apt-get upgrade -y && apt-get clean
RUN apt-get install -y libeina=0.9.9.063-alt0.M51.1 && \
apt-get install -y libeet=1.2.3-alt0.M51.1 && \
apt-get install -y libevas=0.9.9.063-alt0.M51.1 && \
apt-get install -y libecore=0.9.9.063-alt0.M51.1 && \
apt-get install -y libembryo=0.9.9.063-alt0.M51.1 && \
apt-get install -y libedje=0.9.93.063-alt0.M51.1 && \
apt-get install -y libefreet=0.5.0.063-alt0.M51.1 && \
apt-get install -y libedbus=0.5.0.063-alt0.M51.1 && \
apt-get install -y e17=0.16.999.063-alt0.M51.1

CMD /bin/bash
